onSwap integration
HaloDAO/amm-contracts pull request #10
Opened 2022-05-09 10:55 UTC by 0xAplki

## Description of Changes
Passing tests for current identified test cases. Ready for demo

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-583)

## How To Test

Run all pool tests using the command `yarn test-pool`

### Developer Checklist:

- [ ] I have followed the guidelines in our Contributing document
- [ ] This PR has a corresponding JIRA ticket
- [ ] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [ ] I have successfully ran tests locally
- [ ] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] I have successfully ran tests locally

2022-05-18 12:08 UTC, ctverceles requested changes
hey @0xAplki just initial look through: all tests passing, left some comments. 

Ill do another pass to check the scenario flow against the sheet khidir made

2022-05-20 10:05 UTC, 0xAplki commented
Note: this is for the demo iteration, to be merged for better PR review. Thanks!

2022-05-23 00:36 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(beforeTradeUserfxPHPBalance, 'Unexpected fxPHP User Balance').to.be.lt(afterTradeUserfxPHPBalance)
resolving since @0xAplki mentioned we'll improve this in https://github.com/HaloDAO/amm-contracts/pull/11

2022-05-23 00:37 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(beforeTradeUSDCPoolBalance, 'Unexpected USDC Vault Balance').to.be.lt(afterTradeUSDCPoolBalance)
resolving since @0xAplki mentioned we'll improve this in https://github.com/HaloDAO/amm-contracts/pull/11

2022-05-23 00:37 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(beforeTradeUSDCPoolBalance, 'Unexpected USDC Vault Balance').to.be.gt(afterTradeUSDCPoolBalance)
resolving since @0xAplki mentioned we'll improve this in https://github.com/HaloDAO/amm-contracts/pull/11

2022-05-23 00:37 UTC, ctverceles commented on tests/local/pool.test.ts
> +    expect(beforeTradeUSDCPoolBalance, 'Unexpected USDC Vault Balance').to.be.lt(afterTradeUSDCPoolBalance)
resolving since @0xAplki mentioned we'll improve this in https://github.com/HaloDAO/amm-contracts/pull/11

2022-05-23 00:37 UTC, ctverceles commented on tests/local/pool.test.ts
> +    // const THRESHOLD = BigNumber.from(0.5)
resolving since @0xAplki mentioned we'll improve this in https://github.com/HaloDAO/amm-contracts/pull/11

2022-05-23 00:37 UTC, ctverceles approved these changes
Approving since @0xAplki mentioned we'll improve mentioned points in https://github.com/HaloDAO/amm-contracts/pull/11. This merge is just to simplify code review

2022-05-23 01:28 UTC, schystz approved these changes
LGTM

2022-05-23 01:28 UTC, schystz commented on contracts/FXPool.sol
> +    event Trade(
Should this be `OnTrade` to be consistent with the other 2 event names?

```suggestion
    event OnTrade(
```

2022-05-23 03:11 UTC, 0xAplki commented on contracts/FXPool.sol
> +    event Trade(
i think its an event thing but not a hook? since that naming for the hooks, if you agree

2022-05-23 03:22 UTC, merged